baseURL = 'https://intelitrader.github.io/intelitrader'
languageCode = 'en-us'
title = 'My New Hugo Site'

disqusShortname  = 'intelitrader-blog-sample-1'

[permalinks]
    [permalinks.page]
        posts = '/articles/:title/'
    [permalinks.section]
        posts = '/artciles/'
[params]
    enableComments = true
    mermaid = true
