baseURL = 'https://blog.intelitrader.com.br'
languageCode = 'en-us'
title = 'Intelitrader Blog'

[menu]
[[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1

[[menu.main]]
    name = 'Posts'
    url = '/posts'
    weight = 2

[[menu.main]]
    name = 'Sobre'
    url = 'https://www.intelitrader.com.br/pt/sobre.html'
    weight = 3

[Params]
    subtitle = 'Especialistas em soluções para corretoras, exchanges, bancos e assets.'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files