baseURL = 'https://intelitrader.github.io'
languageCode = 'en-us'
title = 'Intelitrader Blog'

[menu]
[[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1

[[menu.main]]
    name = 'Posts'
    url = '/posts'
    weight = 2

[[menu.main]]
    name = 'Resume'
    url = '/cv/'
    weight = 3

[Params]
    subtitle = 'Tecnologia focada em mercado financeiro'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files