baseURL = 'https://intelitrader.github.io/intelitrader'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'mini'

disqusShortname  = 'intelitrader-blog-sample-1'

[params]
    enableComments = true
