baseURL = 'https://blog.intelitrader.com.br'
languageCode = 'en-us'
title = 'Intelitrader Blog'

[menu]
[[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1

[[menu.main]]
    name = 'Posts'
    url = '/posts'
    weight = 2

[Params]
    subtitle = 'subtitle'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files